name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs only when new changes are merged to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=mydockerhub/my-microservice  # Change per service
        TAG=${{ github.sha }}  # Use commit SHA as tag
        docker build -t $IMAGE_NAME:$TAG .
        docker push $IMAGE_NAME:$TAG

  \
