name: Run Python Test Script

on:
  push:
    branches:
      - main  # Or specify any other branch you want

jobs:
  test:
    runs-on: ubuntu-latest  # You can use other OS like 'windows-latest' or 'macos-latest'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Use the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # If you have any dependencies listed in a requirements.txt file

    - name: Run the test.py script
      run: |
        python tests/unit_tests.py
